# Copyright (c) 2019 Zededa, Inc.
# SPDX-License-Identifier: Apache-2.0

version: '3'
services:
  adam:
    build: .
    image: zededa/adam
    ports:
      - "8080:8080"
    volumes:
      - ./run:/adam/run


